// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import type React from "react"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { headers } from "next/headers"
import "./globals.css"
import { Navigation } from "@/components/navigation"
import ContextProvider from "../../context/index"
import { Toaster } from "sonner"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "NFT Creator Platform",
  description: "Create and mint NFTs with creator rewards",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider cookies={(await headers()).get('cookie')}>
          <Navigation />
          <main>{children}</main>
          <Toaster 
            position="top-right"
            toastOptions={{
              style: {
                background: 'rgb(255, 255, 255)',
                border: '1px solid rgb(229, 231, 235)',
                color: 'rgb(17, 24, 39)',
              },
            }}
          />
        </ContextProvider>
      </body>
    </html>
  )
}
